### ISSUE TITLE
사용자 정보 API 설계 및 구현

### ISSUE THREAD

**Issue by N0N4M3D-b** [g3un/sp1-backend#1]
ㅈㄱㄴ

**Comment by N0N4M3D-b** [comment]
넷플릭스 로그인 기능과 파싱 기능 구현부터 ㄱ

**Comment by g3un** [comment]
테스트하는 계정이 구독을 안 한 상태라서 계정 정보 구조체 같은걸 어캐 잡아야할 지 모르겠음
지금은 알 수 있는게 구독 여부, 계정 내 아이디 이렇게 두 개가 다임

**Comment by N0N4M3D-b** [comment]
처리하고 결과 보낼때 json 형식으로 보내는데 status code랑 메시지 같이 보내주면 DB나 프론트엔드 쪽에서 처리하기 편할 듯 함

로그인 성공 시
{
    "code" : 200,
    "message" : "netflix login success",
    "result" : {
        "id" : "abcd",
        "pw" : "1234",
        "payment" : {
                "type" : "~~~",
                "detail" : "~~~",
                "next" : "~~~",
         }
        "membership" : {
                "type": 1,
                "cost": 1
        }
}

로그인 실패 시
{
    "code" : 404,
    "message" : "netflix login error"
}

요런 식으로

**Comment by g3un** [comment]
> 처리하고 결과 보낼때 json 형식으로 보내는데 status code랑 메시지 같이 보내주면 DB나 프론트엔드 쪽에서 처리하기 편할 듯 함
> 
> 로그인 성공 시
> 
> ```json
> {
>     "code" : 200,
>     "message" : "netflix login success",
>     "result" : {
>         "id" : "abcd",
>         "pw" : "1234",
>         "payment" : {
>                 "type" : "~~~",
>                 "detail" : "~~~",
>                 "next" : "~~~",
>          },
>         "membership" : {
>                 "type": 1,
>                 "cost": 1
>         }
>     }
> }
> ```
> 
> 로그인 실패 시
> 
> ```json
> {
>     "code" : 404,
>     "message" : "netflix login error"
> }
> ```
> 
> 요런 식으로

찾아보니까 status code는 헤더에 담길래, message만 넣음
