### ISSUE TITLE
웨이브 로그인처리

### ISSUE THREAD

**Issue by cjh4629** [g3un/sp1-backend#5]
점유율 순위순서로 간다

**Comment by g3un** [comment]
공용 아이디 있음?

**Comment by g3un** [comment]
계정 정보가 틀리면 alert 창이 뜨는데, 그 창을 핸들링하는 방법을 쓰려면 함수 구조를 바꿔야 함.
보니까 구조가 좀 복잡해질 거 같아서 일단 그 부분 넘기고 코딩했고, 맞는 계정 정보를 입력했을 땐 정상적으로 작동하는 거까지 확인함.

**Comment by g3un** [comment]
> alert는 프론트에서 처리로 바꿨고
> sns로그인 구현해볼꺼?

ㄴㄴ
